### ISSUE TITLE
Cannot import name 'get_grad_norm' from 'lib.misc'

### ISSUE THREAD

**Issue by yangyj2000** [nktoan/risk-distribution-matching#1]
I can't find the get_grad_norm, Nonparametric in the file 'lib.misc' when compile the file 'algorithms.py' in CMNIST. Could you tell me where are they?

**Comment by yangyj2000** [comment]
I have downloaded the directory 'lib' from 'https://github.com/facebookresearch/DomainBed/tree/main/domainbed/lib'

**Comment by nktoan** [comment]
Hi @yangyj2000 ,

Thank you for your interest in our work. For the CMNIST experiment, we adapted the code from [this repository](https://github.com/cianeastwood/qrm/tree/main/CMNIST). I am currently on leave, so please take the "lib" folder from that repository, as I realized it was not included in my last commit. If you encounter any further issues, feel free to reach out. I plan to update our repository next week.

Cheers,
Toan Nguyen.

**Comment by yangyj2000** [comment]
Thank you for your answer!
